name: ci

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up GO 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0

      - name: Lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make lint

  unit:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up GO 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Test
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make test
